/**
 * GluonDatabaseAdapter
 *
 * Defines the full database contract for gluon-ai. Implement this interface
 * to connect gluon to any ORM or database client (Prisma, Drizzle, Mongoose,
 * raw SQL, etc.).
 *
 * The built-in `createPrismaAdapter()` factory satisfies this interface for
 * any Prisma-compatible database (PostgreSQL, MySQL, SQLite, SQL Server).
 *
 * Generated stub path for custom adapters:  ./agent/db.ts
 */

export interface GluonChatRow {
  id: string;
  userId: string;
  title: string;
  uiMessages: unknown;
  activeJobRunId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface GluonJobRunRow {
  id: string;
  chatId: string;
  userId: string;
  status: string;
  bullmqJobId: string | null;
  currentRoundIndex: number;
  pendingConfirmationToolCallId: string | null;
  /** Deserialized array — adapters must return this as a plain string[]. */
  confirmationResolvedIds: string[];
  lastPublishedSeq: number;
  errorMessage: string | null;
  startedAt: Date | null;
  finishedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface GluonDatabaseAdapter {
  chat: {
    /** Create a new chat row; ID is generated by the adapter. */
    create(userId: string, title?: string): Promise<GluonChatRow>;

    /**
     * Upsert a chat row — create if absent, touch `updatedAt` if present.
     * `uiMessages` is only written on create.
     */
    upsert(chatId: string, userId: string, uiMessages?: unknown): Promise<void>;

    /** Return the raw `uiMessages` JSON value (typically `UIMessage[]`). */
    loadMessages(chatId: string): Promise<unknown>;

    /**
     * Overwrite `uiMessages` for an existing chat row.
     * - `activeJobRunId` — also update the active run pointer when provided.
     * - `skipIfMissing` — silently skip (no error) if the chat no longer exists.
     */
    saveMessages(
      chatId: string,
      msgs: unknown,
      opts?: { activeJobRunId?: string | null; skipIfMissing?: boolean },
    ): Promise<void>;

    /** List all chats for a user, ordered newest first. */
    listForUser(userId: string): Promise<GluonChatRow[]>;

    /** Return `{ id }` if the chat exists and belongs to `userId`, else null. */
    findOwned(chatId: string, userId: string): Promise<{ id: string } | null>;

    /** Return `{ title }` for a chat, or null if not found. */
    findTitle(chatId: string): Promise<{ title: string } | null>;

    /** Return `{ id, activeJobRunId }` if owned, else null. */
    findWithActiveJob(
      chatId: string,
      userId: string,
    ): Promise<{ id: string; activeJobRunId: string | null } | null>;

    /**
     * Return the full chat row for use in run lifecycle events.
     * Returns null if the chat does not exist or is not owned by `userId`.
     */
    findForRun(chatId: string, userId: string): Promise<GluonChatRow | null>;

    /** Update the chat title. */
    updateTitle(chatId: string, title: string): Promise<void>;

    /** Point `activeJobRunId` at `runId`. */
    setActiveRun(chatId: string, runId: string): Promise<void>;

    /**
     * Clear `activeJobRunId` only if it currently equals `runId`.
     * Safe to call concurrently — no-op if already cleared.
     */
    clearActiveRunIfMatches(chatId: string, runId: string): Promise<void>;

    /** Delete a chat and its job runs (cascade). */
    delete(chatId: string): Promise<void>;
  };

  run: {
    /** Create a new QUEUED job run. */
    create(chatId: string, userId: string): Promise<GluonJobRunRow>;

    /** Attach a BullMQ job ID to an existing run. */
    setBullmqId(runId: string, bullmqJobId: string): Promise<void>;

    /** Fetch a run by its primary key. */
    findById(runId: string): Promise<GluonJobRunRow | null>;

    /**
     * Return the active run for a chat (QUEUED | RUNNING | AWAITING_USER),
     * most recently created first.
     */
    findActiveForChat(chatId: string): Promise<GluonJobRunRow | null>;

    /** Fetch a run that belongs to the given user. */
    findOwned(runId: string, userId: string): Promise<GluonJobRunRow | null>;

    /** Advance the round counter. */
    setRound(runId: string, nextRoundIndex: number): Promise<void>;

    /** Transition to AWAITING_USER and record the pending tool-call ID. */
    markAwaitingUser(runId: string, toolCallId: string): Promise<void>;

    /** Transition back to RUNNING and clear the pending tool-call ID. */
    clearAwaitingUser(runId: string): Promise<void>;

    /**
     * Atomic: AWAITING_USER → RUNNING.
     * Returns `true` if the row was claimed (status was AWAITING_USER and matched
     * the userId + chatId).  Returns `false` if the row was already in another
     * state (idempotent re-approval is handled by the caller).
     */
    claimApproval(runId: string, userId: string, chatId: string): Promise<boolean>;

    /** Append a resolved tool-call ID (idempotent). */
    appendConfirmationResolved(runId: string, toolCallId: string): Promise<void>;

    /** Transition to any terminal or intermediate status. */
    transition(
      runId: string,
      status: string,
      extra?: { errorMessage?: string | null },
    ): Promise<void>;

    /**
     * Atomic increment of `lastPublishedSeq`.
     * Returns the new (post-increment) value.
     */
    incrementSeq(runId: string): Promise<number>;

    /**
     * `UPDATE … SET lastPublishedSeq = seq
     *  WHERE id = runId AND lastPublishedSeq < seq`
     *
     * No-op if the stored value is already >= seq.
     */
    setSeqIfHigher(runId: string, seq: number): Promise<void>;
  };
}
