
import * as path from "node:path";

// The Prisma client is generated from the package's own prisma/schema.prisma into
// prisma/generated/ (relative to the package root). It is generated by the
// `postinstall` script on npm install, or explicitly by `npx gluon-ai init`.
//
// At runtime in dist/server.js (CJS), __dirname is the dist/ directory, so
// path.join(__dirname, "..", "prisma", "generated") → <pkg-root>/prisma/generated/.
//
// We use a dynamic require rather than a static import so that:
//   1. tsup/esbuild does not try to bundle the generated client.
//   2. The require resolves at runtime after the client has been generated.
//
const { PrismaClient: PrismaClientCtor } = require(
  path.join(__dirname, "..", "prisma", "generated"),
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
) as { PrismaClient: new (opts?: Record<string, unknown>) => any };

const globalForPrisma = globalThis as unknown as {
  agentPrisma: ReturnType<typeof makePrismaClient> | undefined;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyPrismaClient = any;

function makePrismaClient(): AnyPrismaClient {
  const databaseUrl =
    process.env.AGENT_DATABASE_URL ?? process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error(
      "AGENT_DATABASE_URL (or DATABASE_URL) environment variable is not set. " +
        "Run `npx gluon-ai init` to configure your database connection.",
    );
  }
  return new PrismaClientCtor({
    datasources: { db: { url: databaseUrl } },
  });
}

export function getPrismaClient(): AnyPrismaClient {
  if (globalForPrisma.agentPrisma) return globalForPrisma.agentPrisma;
  const client = makePrismaClient();
  if (process.env.NODE_ENV !== "production") {
    globalForPrisma.agentPrisma = client;
  }
  return client;
}

export const prisma: AnyPrismaClient = new Proxy({} as AnyPrismaClient, {
  get(_target, prop) {
    return getPrismaClient()[prop];
  },
});
